/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface FefeDropdown {
      'values': string;
    }
  }

  interface HTMLFefeDropdownElement extends StencilComponents.FefeDropdown, HTMLStencilElement {}

  var HTMLFefeDropdownElement: {
    prototype: HTMLFefeDropdownElement;
    new (): HTMLFefeDropdownElement;
  };
  interface HTMLElementTagNameMap {
    'fefe-dropdown': HTMLFefeDropdownElement;
  }
  interface ElementTagNameMap {
    'fefe-dropdown': HTMLFefeDropdownElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'fefe-dropdown': JSXElements.FefeDropdownAttributes;
    }
  }
  namespace JSXElements {
    export interface FefeDropdownAttributes extends HTMLAttributes {
      'values'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;